local mg		= require "moongen"
local memory	= require "memory"
local device	= require "device"
local stats		= require "stats"
local log 		= require "log"
local ip4		= require "proto.ip4"
local libmoon	= require "libmoon"
local dpdkc		= require "dpdkc"
local ffi		= require "ffi"
local syscall	= require "syscall"


function configure(parser)
    -- do nothing, just check parse errors
	function convertMac_fake(str)
		mac = parseMacAddress(str, true)
		if not mac then
			parser:error("failed to parse MAC "..str)
		end
		return str
	end

	function convertTime(str)
		local pattern = "^(%d+)([mu]?s)$"
		local _, _, n, unit = string.find(str, pattern)
		if not (n and unit) then
			parser:error("failed to parse time '"..str.."', it should match '"..pattern.."' pattern")
		end
		return {n=tonumber(n), unit=unit}
	end

	parser:description("Redirects stream between devices, optionally mangling and delaying data.")
	parser:argument("srcDev", "Source device."):convert(tonumber)
	parser:argument("dstDev", "Destination device."):convert(tonumber)
	parser:option("-n", "Number of threads."):convert(tonumber):default(1)
	parser:option("-d --destination", "Rewrite destination IP.")
	parser:option("-m --ethDst", "Rewrite destination MAC."):convert(convertMac_fake)
	parser:option("--delay", "Delay in us."):convert(tonumber):default(0)
	parser:option("--buf", "Buffer size."):convert(tonumber):default(63)
	parser:option("-l --max-pktlen", "Maximum packet length."):convert(tonumber):default(60)
	parser:flag("--feed-self", "Do not drop traffic generated by ourselves.")
	parser:flag("--fake-write", "Do not actually issue traffic.")
	parser:flag("--debug", "Debug ring buffer.")
end

local shm_filename = "/MoonGen"

local function setup(isMaster, taskNum, args)
	if args.debug then
		log:setLevel("DEBUG")
	end

	local cfg = {}
	local shm_filename = shm_filename .. "-" .. tostring(taskNum)

	cfg.chunkSize = args.buf + 1
	cfg.packetSpace = args.max_pktlen + 4
	local delay = args.delay; if delay <= 0 then delay = 1 end
	local extra = 10.0 -- just in case
	local _, e = math.frexp(14.88 * delay * extra / args.buf)
	if e < 2 then e = 2 end
	cfg.ringSize = bit.lshift(1, e)
	if isMaster and taskNum == 1 then
		log:info("buf size: %d, ringSize: %d, e: %d", args.buf, cfg.ringSize, e)
	end
	cfg.ringDblSize = cfg.ringSize * 2

	local oflags
	if isMaster then oflags = "CREAT,RDWR,EXCL" else oflags = "RDWR" end

	local shm_fd, err = syscall.shm_open(shm_filename, oflags, "RUSR,WUSR")
	if not shm_fd then
		if err.EXIST then
			-- try to unlink and retry to open
			syscall.shm_unlink(shm_filename)
			shm_fd, err = syscall.shm_open(shm_filename, oflags, "RUSR,WUSR")
		end
		if not shm_fd then
			errorf("shm_open(\"%s\", ...) failed: %s", shm_filename, err)
		end
	end
	local ringRawSize = cfg.ringSize * cfg.chunkSize * cfg.packetSpace
	local shm_size = ringRawSize + 8
	local ok, err = syscall.ftruncate(shm_fd, shm_size)
	if not ok then
		errorf("ftruncate(...) failed: %s", err)
	end
	local ptr, err = syscall.mmap(nil, shm_size, "READ,WRITE", "SHARED", shm_fd, 0)
	if not ptr then
		errorf("nmap(...) failed: %s", err)
	end
	cfg.ringBufferRaw = ffi.cast("uint8_t*", ptr)
	cfg.ax_ptr = ffi.cast("volatile uint32_t*", cfg.ringBufferRaw+ringRawSize)
	cfg.bx_ptr = ffi.cast("volatile uint32_t*", cfg.ringBufferRaw+ringRawSize+4)

	if isMaster then
		cfg.ax_ptr[0] = 0
		cfg.bx_ptr[0] = 0
		cfg.cleanupFunc = function()
			syscall.munmap(ptr, shm_size)
			syscall.close(shm_fd)
			syscall.shm_unlink(shm_filename)
		end
	else
		cfg.cleanupFunc = function() syscall.munmap(ptr, shm_size); syscall.close(shm_fd) end
	end

	return cfg
end

function master(args)
	local cfgs = {}
	for i = 1, args.n do
		cfgs[i] = setup(true, i, args)
	end

	local srcDev, dstDev
	if args.srcDev == args.dstDev then
		srcDev = device.config{port = args.srcDev, rxQueues = args.n, txQueues = args.n}
		dstDev = srcDev
	else
		srcDev = device.config{port = args.srcDev, rxQueues = args.n}
		dstDev = device.config{port = args.dstDev, txQueues = args.n}
	end
	srcDev:wait()
	dstDev:wait()

	for i = 0, args.n - 1 do
		mg.startTask("task_read", i+1, srcDev:getRxQueue(i), dstDev:getMac(true), args)
		mg.startTask("task_write", i+1, dstDev:getTxQueue(i), args)
	end
	
	mg.waitForTasks()
	for _, cfg in ipairs(cfgs) do cfg.cleanupFunc() end
end

local function gettimeofday_n()
	local sec, usec = gettimeofday()
	return tonumber(sec), tonumber(usec)
end

local zero16 = hton16(0)

function task_read(taskNum, rxQ, ethSelf, args)
	local cfg = setup(false, taskNum, args)

	local rxStats = stats:newDevRxCounter(rxQ, "plain")
	local totStats = stats:newPktRxCounter("total:" .. tostring(taskNum))
	local ringStats = stats:newPktRxCounter("ring:" .. tostring(taskNum))
	local manStats = stats:newManualRxCounter("man:" .. tostring(taskNum))
	local timesBufferFull = 0

	local mem = memory.createMemPool()
	local bufs_read = mem:bufArray(cfg.chunkSize - 1)

	-- ring buffer pointers (not using "tx", "rx" due to confusion), ax is to be "greater" than bx
	local ax, bx = 0, 0

	while mg.running() do
		bx = cfg.bx_ptr[0]
		-- TODO: use bit operations
		if (ax - bx) % cfg.ringDblSize ~= cfg.ringSize then
			local sec, usec = gettimeofday_n()
			local rx = rxQ:recv(bufs_read)
			bufs_read:freeAfter(rx)
			manStats:update(rx, 0)

			local chunkIdx = ax % cfg.ringSize
			local j = 0
			for i = 1, rx do
				local buf = bufs_read[i]
				local pkt = buf:getTcpPacket(ipv4)
				local bufSize = buf:getSize()

				local pkt_raw = cfg.ringBufferRaw + ((chunkIdx * cfg.chunkSize + j) * cfg.packetSpace)
				if bufSize <= args.max_pktlen and (args.feed_self or pkt.eth.src:get() ~= ethSelf)
				then
					ringStats:countPacket(buf)
					ffi.cast("uint32_t*", pkt_raw)[0] = bufSize
					ffi.copy(pkt_raw + 4, buf:getRawPacket(), bufSize)
					j = j + 1
				end
				totStats:countPacket(buf)
			end

			local meta_raw = ffi.cast("volatile uint32_t*", cfg.ringBufferRaw + (((chunkIdx + 1) * cfg.chunkSize - 1) * cfg.packetSpace))
			meta_raw[0], meta_raw[1], meta_raw[2] = rx, sec, usec
			log:debug("READ-%d %03x, %03x", taskNum, ax, bx)
			ax = (ax + 1) % cfg.ringDblSize
			cfg.ax_ptr[0] = ax

			rxStats:update()
			totStats:update()
			ringStats:update()
		else
			if timesBufferFull == 0 then
				log:warn("Buffer is full")
			end
			timesBufferFull = timesBufferFull + 1
		end
	end

	rxStats:finalize()
	totStats:finalize()
	ringStats:finalize()
	manStats:finalize()
	if timesBufferFull ~= 0 then
		log:warn("Buffer was full %d times", timesBufferFull)
	end
	cfg.cleanupFunc()
end

function task_write(taskNum, txQ, args)
	local cfg = setup(false, taskNum, args)

	local ipDst = args.destination and parseIPAddress(args.destination)
	local ethDst = args.ethDst and parseMacAddress(args.ethDst, true)
	local ethSrc = txQ.dev:getMac(true)
	
	local txStats = stats:newDevTxCounter(txQ, "plain")

	local mem = memory.createMemPool()
	local bufs_write = mem:bufArray(cfg.chunkSize - 1)

	-- ring buffer pointers (not using "tx", "rx" due to confusion), ax is to be "greater" than bx
	local ax, bx = 0, 0

	local function do_write()
		ax = cfg.ax_ptr[0]
		-- TODO: use bit operations
		while (ax - bx) % cfg.ringDblSize ~= 0 do
			local chunkIdx = bx % cfg.ringSize
			local meta_raw = ffi.cast("volatile uint32_t*", cfg.ringBufferRaw + (((chunkIdx + 1) * cfg.chunkSize - 1) * cfg.packetSpace))
			local sec, usec = gettimeofday_n()
			local delta_usec = (sec - meta_raw[1]) * 1000000 + (usec - meta_raw[2])

			if delta_usec > args.delay then
				log:debug("WRITE-%d %03x, %03x, delta: %d", taskNum, ax, bx, delta_usec)

				if not args.fake_write then
					local nRecvd = meta_raw[0]
					if nRecvd > cfg.chunkSize - 1 then
						nRecvd = cfg.chunkSize - 1
						log:warn("Probably garbage in ring buffer (nRecvd): %d > %d", nRecvd, cfg.chunkSize-1)
					end
					bufs_write:resize(nRecvd)
					bufs_write:alloc(args.max_pktlen)

					local i = 0
					for j = 0, nRecvd-1 do
						local pkt_raw = cfg.ringBufferRaw + ((chunkIdx * cfg.chunkSize + j) * cfg.packetSpace)
						local pktSize = ffi.cast("uint32_t*", pkt_raw)[0]
						if pktSize ~= 0 then
							i = i + 1
							local buf = bufs_write[i]
							buf:setSize(pktSize)
							ffi.copy(buf:getData(), pkt_raw+4, pktSize)

							local pkt = buf:getTcpPacket(ipv4)
							if pkt.ip4:getProtocol() == ip4.PROTO_TCP then
								if ethDst then
									pkt.eth.dst:set(ethDst)
									pkt.eth.src:set(ethSrc)
								end
								if ipDst then pkt.ip4.dst:set(ipDst) end
								--pkt.ip4:setChecksum(0)
								pkt.ip4.cs = zero16 -- FIXME: setChecksum() is extremely slow
							end
						end
					end
					if i ~= 0 then
						bufs_write:resize(i)
						bufs_write:offloadTcpChecksums(ipv4)
						txQ:send(bufs_write)
					end
				end
				txStats:update()

				bx = (bx + 1) % cfg.ringDblSize
				cfg.bx_ptr[0] = bx
			else
				if delta_usec < 0 then
					log:warn("Oops, something wrong with time")
				end
				return
			end
		end
	end

	while mg.running() do
		do_write()
	end

	txStats:finalize()
	cfg.cleanupFunc()
end
